#!/usr/bin/env bash
#installing the nginx library on the server and making sure it responds at the 80 port

sudo apt-get update
sudo apt-get install -y nginx

echo "Holberton School" | sudo tee /var/www/html/index.html

sudo /etc/init.d/nginx restart
